import { allSkins } from '@/lib/brand';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Every skin', robots: { index: false, follow: false } };

export default function DemoIndex() {
  const skins = allSkins();
  return (
    <main className="wrap">
      <h1 className="ask">One build, {skins.length} storefronts.</h1>
      <p className="sub">
        Same code, same finder, same checkout. The name, address, colours and hours come from
        whichever dispensary you open. Generated by <code>scripts/skin.mjs</code> off
        the 248 licensed Minnesota retailers in <code>data/prospects.json</code>.
      </p>
      {skins.map((s) => (
        <a className="alt" key={s.slug} href={`/demo/${s.slug}`}>
          <span className="an">{s.storeName}
            <span className="am">
              {s.stores[0]?.street}, {s.stores[0]?.city}
              {s.scan?.platforms?.length ? ` · runs ${s.scan.platforms.join(', ')}` : ''}
            </span>
          </span>
          <span aria-hidden style={{
            width: 22, height: 22, borderRadius: 6, background: s.colors.accent,
            border: '1px solid rgba(0,0,0,.2)', flex: '0 0 auto',
          }} />
        </a>
      ))}
    </main>
  );
}
