import brandJson from '@/brand.json';
import skinIndex from '@/data/skins/index.json';

export interface Store {
  id: string; name: string; street: string; city: string; state: string; zip: string;
  lat: number; lng: number; phone: string;
  /** null = not verified for this location. Never render invented hours. */
  hours: Record<string, string> | null;
}

export interface Scan {
  ok: boolean; url?: string | null; final?: string; ms?: number; bytes?: number;
  https?: boolean; viewport?: boolean; title?: string; meta_desc?: boolean;
  jsonld?: number; iframes?: number; scripts?: number; platforms?: string[]; error?: string;
}

export interface Brand {
  slug: string;
  storeName: string; legalName: string; tagline: string; headline: string;
  wordmark: string; wordmarkNote: string;
  colors: { accent: string; ground: string; dial: string };
  colorSource?: string;
  phone: string; email: string; licenseNumber: string; licenseNote?: string;
  url: string; sourceUrl: string; verifiedOn: string;
  rating?: number | null; reviews?: number | null; openerFact?: string;
  scan?: Scan;
  stores: Store[];
}

export const RISE = brandJson as unknown as Brand;

/** Every skin the repo ships, by slug. Generated by scripts/skin.mjs. */
const SKINS = skinIndex as unknown as Record<string, Brand>;

export function loadSkin(slug: string | undefined | null): Brand | null {
  if (!slug || slug === RISE.slug) return RISE;
  return SKINS[slug] ?? null;
}

export function allSkins(): Brand[] {
  return [RISE, ...Object.values(SKINS)].sort((a, b) => a.storeName.localeCompare(b.storeName));
}

export function storeById(b: Brand, id: string): Store | undefined {
  return b.stores.find((s) => s.id === id);
}

export const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const;

/**
 * MN OCM advertising warning. Read verbatim off a licensed Minnesota retailer's
 * live site (risecannabis.com, 2026-09-15) - Minn. Stat. 342.64 subd. 1(4)
 * requires "a warning as specified by the office regarding impairment and health
 * risks" but does not print the text in the statute itself.
 * See docs/compliance-mn.md before changing a word of this.
 */
export const MN_WARNING =
  'Warning: Cannabis products are not for use by anyone under the age of 21. ' +
  'Cannabis use may cause drowsiness, affect focus, reaction time, and decision-making. ' +
  'These products are not evaluated or approved by the FDA. Pregnant people should avoid ' +
  'cannabis due to the risk of low birth weight, premature birth, stillbirth, and harm to ' +
  'fetal brain development.';

export const HONESTY_LINE =
  'Independent concept by Brick & Mortar. Not affiliated with RISE or Green Thumb Industries.';

export function honestyLine(b: Brand): string {
  if (b.slug === RISE.slug) return HONESTY_LINE;
  return `Independent concept by Brick & Mortar. Not affiliated with ${b.storeName}.`;
}
